[package]
name = "soft_ratatui"
version = "0.0.3"
edition = "2021"
authors = ["gold-silver-copper"]

include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

description = "Software rendering for ratatui. TUI everywhere."
license = "MIT OR Apache-2.0"
repository = "https://github.com/gold-silver-copper/soft_ratatui"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Optional dependencies
cosmic-text = { version = "0.14.2", features = ["shape-run-cache"] }


# Other dependencies
ratatui = { version = "0.29.0", default-features = false }

[dev-dependencies]
color-eyre = "0.6.3"
itertools = "0.14.0"
palette = "0.7.6"


[profile.release]
#opt-level = 1
#lto = true # Enable link-time optimization
#codegen-units = 1 # Better optimizations, slightly slower compile
#panic = "abort"   # Smaller binary if you don't need backtraces
#strip = "symbols" # Remove debug symbols (unless you need them)

# Uncomment this for even smaller output (disable debug info)
#debug = true
